// California cities to counties mapping
export const cityToCounty: Record<string, string> = {
  // Alameda County
  'alameda': 'Alameda',
  'albany': 'Alameda',
  'berkeley': 'Alameda',
  'dublin': 'Alameda',
  'emeryville': 'Alameda',
  'fremont': 'Alameda',
  'hayward': 'Alameda',
  'livermore': 'Alameda',
  'newark': 'Alameda',
  'oakland': 'Alameda',
  'piedmont': 'Alameda',
  'pleasanton': 'Alameda',
  'san leandro': 'Alameda',
  'union city': 'Alameda',

  // Los Angeles County (major cities)
  'los angeles': 'Los Angeles',
  'long beach': 'Los Angeles',
  'glendale': 'Los Angeles',
  'santa clarita': 'Los Angeles',
  'lancaster': 'Los Angeles',
  'palmdale': 'Los Angeles',
  'pomona': 'Los Angeles',
  'torrance': 'Los Angeles',
  'pasadena': 'Los Angeles',
  'el monte': 'Los Angeles',
  'downey': 'Los Angeles',
  'inglewood': 'Los Angeles',
  'west covina': 'Los Angeles',
  'norwalk': 'Los Angeles',
  'burbank': 'Los Angeles',
  'compton': 'Los Angeles',
  'south gate': 'Los Angeles',
  'carson': 'Los Angeles',
  'santa monica': 'Los Angeles',
  'whittier': 'Los Angeles',
  'hawthorne': 'Los Angeles',
  'alhambra': 'Los Angeles',
  'lakewood': 'Los Angeles',
  'bellflower': 'Los Angeles',
  'baldwin park': 'Los Angeles',
  'redondo beach': 'Los Angeles',
  'paramount': 'Los Angeles',
  'montebello': 'Los Angeles',
  'monterey park': 'Los Angeles',
  'rosemead': 'Los Angeles',
  'pico rivera': 'Los Angeles',
  'gardena': 'Los Angeles',
  'cerritos': 'Los Angeles',
  'bellingham': 'Los Angeles',
  'lynwood': 'Los Angeles',
  'lynnwood': 'Los Angeles',
  'la puente': 'Los Angeles',
  'arcadia': 'Los Angeles',
  'redlands': 'Los Angeles',
  'manhattan beach': 'Los Angeles',
  'el segundo': 'Los Angeles',
  'hermosa beach': 'Los Angeles',
  'beverly hills': 'Los Angeles',
  'culver city': 'Los Angeles',
  'west hollywood': 'Los Angeles',
  'granada hills': 'Los Angeles',

  // Orange County
  'anaheim': 'Orange',
  'santa ana': 'Orange',
  'irvine': 'Orange',
  'huntington beach': 'Orange',
  'garden grove': 'Orange',
  'orange': 'Orange',
  'fullerton': 'Orange',
  'costa mesa': 'Orange',
  'mission viejo': 'Orange',
  'westminster': 'Orange',
  'newport beach': 'Orange',
  'buena park': 'Orange',
  'lake forest': 'Orange',
  'tustin': 'Orange',
  'yorba linda': 'Orange',
  'san clemente': 'Orange',
  'laguna niguel': 'Orange',
  'la habra': 'Orange',
  'fountain valley': 'Orange',
  'placentia': 'Orange',
  'rancho santa margarita': 'Orange',
  'aliso viejo': 'Orange',
  'cypress': 'Orange',
  'brea': 'Orange',
  'stanton': 'Orange',
  'dana point': 'Orange',
  'laguna beach': 'Orange',
  'laguna hills': 'Orange',
  'seal beach': 'Orange',
  'villa park': 'Orange',
  'los alamitos': 'Orange',

  // San Diego County
  'san diego': 'San Diego',
  'chula vista': 'San Diego',
  'oceanside': 'San Diego',
  'escondido': 'San Diego',
  'carlsbad': 'San Diego',
  'el cajon': 'San Diego',
  'vista': 'San Diego',
  'san marcos': 'San Diego',
  'encinitas': 'San Diego',
  'national city': 'San Diego',
  'la mesa': 'San Diego',
  'santee': 'San Diego',
  'poway': 'San Diego',
  'coronado': 'San Diego',
  'imperial beach': 'San Diego',
  'lemon grove': 'San Diego',
  'la presa': 'San Diego',
  'spring valley': 'San Diego',
  'bonita': 'San Diego',
  'del mar': 'San Diego',
  'solana beach': 'San Diego',

  // Riverside County
  'riverside': 'Riverside',
  'moreno valley': 'Riverside',
  'corona': 'Riverside',
  'temecula': 'Riverside',
  'murrieta': 'Riverside',
  'indio': 'Riverside',
  'palm springs': 'Riverside',
  'hemet': 'Riverside',
  'palm desert': 'Riverside',
  'lake elsinore': 'Riverside',
  'cathedral city': 'Riverside',
  'menifee': 'Riverside',
  'perris': 'Riverside',
  'banning': 'Riverside',
  'beaumont': 'Riverside',
  'coachella': 'Riverside',
  'desert hot springs': 'Riverside',
  'la quinta': 'Riverside',
  'rancho mirage': 'Riverside',
  'indian wells': 'Riverside',
  'bermuda dunes': 'Riverside',
  'thousand palms': 'Riverside',
  'thermal': 'Riverside',
  'mecca': 'Riverside',
  'north shore': 'Riverside',
  'vista santa rosa': 'Riverside',

  // San Bernardino County
  'san bernardino': 'San Bernardino',
  'fontana': 'San Bernardino',
  'rancho cucamonga': 'San Bernardino',
  'ontario': 'San Bernardino',
  'victorville': 'San Bernardino',
  'rialto': 'San Bernardino',
  'upland': 'San Bernardino',
  'chino hills': 'San Bernardino',
  'chino': 'San Bernardino',
  'redlands': 'San Bernardino',
  'apple valley': 'San Bernardino',
  'hesperia': 'San Bernardino',
  'highland': 'San Bernardino',
  'colton': 'San Bernardino',
  'montclair': 'San Bernardino',
  'adelanto': 'San Bernardino',
  'twentynine palms': 'San Bernardino',
  'barstow': 'San Bernardino',
  'yucaipa': 'San Bernardino',
  'loma linda': 'San Bernardino',
  'grand terrace': 'San Bernardino',
  'needles': 'San Bernardino',

  // Santa Clara County (Bay Area)
  'san jose': 'Santa Clara',
  'sunnyvale': 'Santa Clara',
  'santa clara': 'Santa Clara',
  'mountain view': 'Santa Clara',
  'palo alto': 'Santa Clara',
  'milpitas': 'Santa Clara',
  'fremont': 'Santa Clara',
  'cupertino': 'Santa Clara',
  'campbell': 'Santa Clara',
  'morgan hill': 'Santa Clara',
  'gilroy': 'Santa Clara',
  'saratoga': 'Santa Clara',
  'los altos': 'Santa Clara',
  'los altos hills': 'Santa Clara',
  'monte sereno': 'Santa Clara',

  // Contra Costa County
  'antioch': 'Contra Costa',
  'concord': 'Contra Costa',
  'richmond': 'Contra Costa',
  'fremont': 'Contra Costa',
  'hayward': 'Contra Costa',
  'walnut creek': 'Contra Costa',
  // Common short form seen on Kaiser single-auth PDFs for Walnut Creek.
  'walnut': 'Contra Costa',
  'pittsburg': 'Contra Costa',
  'san ramon': 'Contra Costa',
  'martinez': 'Contra Costa',
  'brentwood': 'Contra Costa',
  'oakley': 'Contra Costa',
  'pleasant hill': 'Contra Costa',
  'danville': 'Contra Costa',
  'el cerrito': 'Contra Costa',
  'san pablo': 'Contra Costa',
  'hercules': 'Contra Costa',
  'pinole': 'Contra Costa',
  'clayton': 'Contra Costa',
  'orinda': 'Contra Costa',
  'lafayette': 'Contra Costa',
  'moraga': 'Contra Costa',

  // Sacramento County
  'sacramento': 'Sacramento',
  'elk grove': 'Sacramento',
  'folsom': 'Sacramento',
  'citrus heights': 'Sacramento',
  'rancho cordova': 'Sacramento',
  'galt': 'Sacramento',
  'isleton': 'Sacramento',
  'fair oaks': 'Sacramento',
  'carmichael': 'Sacramento',
  'orangevale': 'Sacramento',
  'antelope': 'Sacramento',
  'north highlands': 'Sacramento',
  'arden arcade': 'Sacramento',
  'gold river': 'Sacramento',
  'rancho murieta': 'Sacramento',
  'elverta': 'Sacramento',
  'rio linda': 'Sacramento',
  'wilton': 'Sacramento',
  'herald': 'Sacramento',
  'walnut grove': 'Sacramento',
  'courtland': 'Sacramento',
  'hood': 'Sacramento',
  'mather': 'Sacramento',
  'mcclellan': 'Sacramento',
  'florin': 'Sacramento',
  'parkway': 'Sacramento',
  'vineyard': 'Sacramento',
  'laguna': 'Sacramento',
  'laguna west': 'Sacramento',

  // Placer County
  'roseville': 'Placer',
  'rocklin': 'Placer',
  'lincoln': 'Placer',
  'auburn': 'Placer',
  'granite bay': 'Placer',
  'loomis': 'Placer',
  'newcastle': 'Placer',
  'penryn': 'Placer',
  'colfax': 'Placer',
  'foresthill': 'Placer',
  'kings beach': 'Placer',
  'tahoe city': 'Placer',

  // Fresno County
  'fresno': 'Fresno',
  'clovis': 'Fresno',
  'selma': 'Fresno',
  'reedley': 'Fresno',
  'sanger': 'Fresno',
  'kingsburg': 'Fresno',
  'parlier': 'Fresno',
  'coalinga': 'Fresno',
  'firebaugh': 'Fresno',
  'fowler': 'Fresno',
  'huron': 'Fresno',
  'mendota': 'Fresno',
  'orange cove': 'Fresno',
  'san joaquin': 'Fresno',

  // Kern County
  'bakersfield': 'Kern',
  'delano': 'Kern',
  'ridgecrest': 'Kern',
  'california city': 'Kern',
  'wasco': 'Kern',
  'shafter': 'Kern',
  'tehachapi': 'Kern',
  'taft': 'Kern',
  'arvin': 'Kern',
  'mcfarland': 'Kern',
  'rosamond': 'Kern',
  'mojave': 'Kern',
  'boron': 'Kern',
  'edwards': 'Kern',
  'edwards afb': 'Kern',
  'inyokern': 'Kern',
  'johannesburg': 'Kern',
  'keene': 'Kern',
  'lamont': 'Kern',
  'buttonwillow': 'Kern',
  'frazier park': 'Kern',
  'lake isabella': 'Kern',
  'kernville': 'Kern',
  'wofford heights': 'Kern',
  'weldon': 'Kern',
  'bodfish': 'Kern',
  'lost hills': 'Kern',
  'maricopa': 'Kern',
  'lebec': 'Kern',
  'onyx': 'Kern',
  'caliente': 'Kern',
  'bear valley springs': 'Kern',
  'golden hills': 'Kern',
  'oildale': 'Kern',

  // Ventura County
  'oxnard': 'Ventura',
  'thousand oaks': 'Ventura',
  'simi valley': 'Ventura',
  'ventura': 'Ventura',
  'camarillo': 'Ventura',
  'moorpark': 'Ventura',
  'port hueneme': 'Ventura',
  'fillmore': 'Ventura',
  'ojai': 'Ventura',
  'santa paula': 'Ventura',

  // San Francisco County
  'san francisco': 'San Francisco',

  // Marin County
  'san rafael': 'Marin',
  'novato': 'Marin',
  'petaluma': 'Marin',
  'mill valley': 'Marin',
  'corte madera': 'Marin',
  'larkspur': 'Marin',
  'sausalito': 'Marin',
  'tiburon': 'Marin',
  'belvedere': 'Marin',
  'ross': 'Marin',
  'san anselmo': 'Marin',
  'fairfax': 'Marin',

  // San Mateo County
  'daly city': 'San Mateo',
  'san mateo': 'San Mateo',
  'redwood city': 'San Mateo',
  'south san francisco': 'San Mateo',
  'san bruno': 'San Mateo',
  'millbrae': 'San Mateo',
  'burlingame': 'San Mateo',
  'foster city': 'San Mateo',
  'san carlos': 'San Mateo',
  'belmont': 'San Mateo',
  'half moon bay': 'San Mateo',
  'pacifica': 'San Mateo',
  'menlo park': 'San Mateo',
  'atherton': 'San Mateo',
  'portola valley': 'San Mateo',
  'woodside': 'San Mateo',
  'hillsborough': 'San Mateo',
  'brisbane': 'San Mateo',
  'colma': 'San Mateo',

  // Solano County
  'vallejo': 'Solano',
  'fairfield': 'Solano',
  'vacaville': 'Solano',
  'suisun city': 'Solano',
  'benicia': 'Solano',
  'dixon': 'Solano',
  'rio vista': 'Solano',

  // Sonoma County
  'santa rosa': 'Sonoma',
  'petaluma': 'Sonoma',
  'rohnert park': 'Sonoma',
  'cotati': 'Sonoma',
  'sebastopol': 'Sonoma',
  'healdsburg': 'Sonoma',
  'windsor': 'Sonoma',
  'sonoma': 'Sonoma',
  'cloverdale': 'Sonoma',
  'guerneville': 'Sonoma',

  // Napa County
  'napa': 'Napa',
  'american canyon': 'Napa',
  'st helena': 'Napa',
  'calistoga': 'Napa',
  'yountville': 'Napa',

  // Stanislaus County
  'modesto': 'Stanislaus',
  'turlock': 'Stanislaus',
  'ceres': 'Stanislaus',
  'riverbank': 'Stanislaus',
  'oakdale': 'Stanislaus',
  'newman': 'Stanislaus',
  'patterson': 'Stanislaus',
  'waterford': 'Stanislaus',
  'hughson': 'Stanislaus',

  // San Joaquin County
  'stockton': 'San Joaquin',
  'tracy': 'San Joaquin',
  'manteca': 'San Joaquin',
  'lodi': 'San Joaquin',
  'ripon': 'San Joaquin',
  'escalon': 'San Joaquin',

  // Tulare County
  'visalia': 'Tulare',
  'tulare': 'Tulare',
  'porterville': 'Tulare',
  'dinuba': 'Tulare',
  'lindsay': 'Tulare',
  'exeter': 'Tulare',
  'farmersville': 'Tulare',
  'woodlake': 'Tulare',

  // Merced County
  'merced': 'Merced',
  'turlock': 'Merced',
  'los banos': 'Merced',
  'atwater': 'Merced',
  'livingston': 'Merced',
  'gustine': 'Merced',

  // Kings County
  'hanford': 'Kings',
  'lemoore': 'Kings',
  'corcoran': 'Kings',
  'avenal': 'Kings',

  // Madera County
  'madera': 'Madera',
  'chowchilla': 'Madera',

  // Monterey County
  'salinas': 'Monterey',
  'monterey': 'Monterey',
  'seaside': 'Monterey',
  'marina': 'Monterey',
  'pacific grove': 'Monterey',
  'carmel': 'Monterey',
  'carmel-by-the-sea': 'Monterey',
  'sand city': 'Monterey',
  'del rey oaks': 'Monterey',
  'gonzales': 'Monterey',
  'greenfield': 'Monterey',
  'king city': 'Monterey',
  'soledad': 'Monterey',

  // San Luis Obispo County
  'san luis obispo': 'San Luis Obispo',
  'paso robles': 'San Luis Obispo',
  'atascadero': 'San Luis Obispo',
  'morro bay': 'San Luis Obispo',
  'pismo beach': 'San Luis Obispo',
  'arroyo grande': 'San Luis Obispo',
  'grover beach': 'San Luis Obispo',
  'cayucos': 'San Luis Obispo',
  'cambria': 'San Luis Obispo',

  // Santa Barbara County
  'santa barbara': 'Santa Barbara',
  'santa maria': 'Santa Barbara',
  'lompoc': 'Santa Barbara',
  'goleta': 'Santa Barbara',
  'carpinteria': 'Santa Barbara',
  'guadalupe': 'Santa Barbara',
  'solvang': 'Santa Barbara',
  'buellton': 'Santa Barbara',

  // Santa Cruz County
  'santa cruz': 'Santa Cruz',
  'watsonville': 'Santa Cruz',
  'capitola': 'Santa Cruz',
  'scotts valley': 'Santa Cruz',

  // Imperial County
  'el centro': 'Imperial',
  'calexico': 'Imperial',
  'imperial': 'Imperial',
  'brawley': 'Imperial',
  'holtville': 'Imperial',
  'calipatria': 'Imperial',
  'westmorland': 'Imperial',

  // Yolo County
  'davis': 'Yolo',
  'woodland': 'Yolo',
  'west sacramento': 'Yolo',
  'winters': 'Yolo',

  // El Dorado County
  'south lake tahoe': 'El Dorado',
  'placerville': 'El Dorado',
  'cameron park': 'El Dorado',
  'el dorado hills': 'El Dorado',

  // Nevada County
  'grass valley': 'Nevada',
  'nevada city': 'Nevada',
  'truckee': 'Nevada',

  // Butte County
  'chico': 'Butte',
  'oroville': 'Butte',
  'paradise': 'Butte',
  'gridley': 'Butte',
  'biggs': 'Butte',

  // Shasta County
  'redding': 'Shasta',
  'anderson': 'Shasta',
  'shasta lake': 'Shasta',

  // Humboldt County
  'eureka': 'Humboldt',
  'arcata': 'Humboldt',
  'fortuna': 'Humboldt',
  'mckinleyville': 'Humboldt',
  'ferndale': 'Humboldt',
  'rio dell': 'Humboldt',
  'blue lake': 'Humboldt',

  // Mendocino County
  'ukiah': 'Mendocino',
  'fort bragg': 'Mendocino',
  'willits': 'Mendocino',
  'point arena': 'Mendocino',

  // Lake County
  'clearlake': 'Lake',
  'lakeport': 'Lake',

  // Sutter County
  'yuba city': 'Sutter',
  'live oak': 'Sutter',

  // Yuba County
  'marysville': 'Yuba',
  'wheatland': 'Yuba',

  // Colusa County
  'colusa': 'Colusa',
  'williams': 'Colusa',

  // Glenn County
  'willows': 'Glenn',
  'orland': 'Glenn',

  // Tehama County
  'red bluff': 'Tehama',
  'corning': 'Tehama',

  // Lassen County
  'susanville': 'Lassen',

  // Modoc County
  'alturas': 'Modoc',

  // Siskiyou County
  'yreka': 'Siskiyou',
  'mount shasta': 'Siskiyou',
  'dunsmuir': 'Siskiyou',

  // Del Norte County
  'crescent city': 'Del Norte',

  // Trinity County
  'weaverville': 'Trinity',

  // Plumas County
  'quincy': 'Plumas',
  'portola': 'Plumas',

  // Sierra County
  'loyalton': 'Sierra',
  'downieville': 'Sierra',

  // Alpine County
  'markleeville': 'Alpine',

  // Mono County
  'bridgeport': 'Mono',
  'mammoth lakes': 'Mono',

  // Inyo County
  'bishop': 'Inyo',
  'lone pine': 'Inyo',
  'independence': 'Inyo',

  // Mariposa County
  'mariposa': 'Mariposa',

  // Tuolumne County
  'sonora': 'Tuolumne',
  'modesto': 'Tuolumne',

  // Calaveras County
  'angels camp': 'Calaveras',
  'san andreas': 'Calaveras',

  // Amador County
  'jackson': 'Amador',
  'plymouth': 'Amador',
  'sutter creek': 'Amador',
  'ione': 'Amador',
};

const ZIP3_TO_COUNTY: Record<string, string> = {
  '900': 'Los Angeles',
  '901': 'Los Angeles',
  '902': 'Los Angeles',
  '903': 'Los Angeles',
  '904': 'Los Angeles',
  '905': 'Los Angeles',
  '906': 'Los Angeles',
  '907': 'Los Angeles',
  '908': 'Los Angeles',
  '910': 'Los Angeles',
  '911': 'Los Angeles',
  '912': 'Los Angeles',
  '913': 'Los Angeles',
  '914': 'Los Angeles',
  '915': 'Los Angeles',
  '916': 'Los Angeles',
  '917': 'Los Angeles',
  '918': 'Los Angeles',
  '919': 'San Diego',
  '920': 'San Diego',
  '921': 'San Diego',
  '922': 'Riverside',
  '923': 'San Bernardino',
  '924': 'San Bernardino',
  '925': 'Riverside',
  '926': 'Orange',
  '927': 'Orange',
  '928': 'Orange',
  '930': 'Ventura',
  '931': 'Santa Barbara',
  '933': 'Kern',
  '937': 'Fresno',
  '939': 'Monterey',
  '940': 'San Mateo',
  '941': 'San Francisco',
  '942': 'Sacramento',
  '943': 'Santa Clara',
  '944': 'San Mateo',
  '946': 'Alameda',
  '947': 'Alameda',
  '948': 'Contra Costa',
  '949': 'Marin',
  '951': 'Santa Clara',
  '952': 'San Joaquin',
  '958': 'Sacramento',
};

// Exact ZIPs for prefixes that span multiple counties (945, 956, 957, 922 Imperial, etc.).
const ZIP5_TO_COUNTY: Record<string, string> = {
  // Imperial County exceptions inside 922 (default 922 is Riverside).
  '92227': 'Imperial',
  '92231': 'Imperial',
  '92232': 'Imperial',
  '92233': 'Imperial',
  '92243': 'Imperial',
  '92244': 'Imperial',
  '92249': 'Imperial',
  '92250': 'Imperial',
  '92251': 'Imperial',
  '92257': 'Imperial',
  '92259': 'Imperial',
  '92273': 'Imperial',
  '92275': 'Imperial',
  '92281': 'Imperial',
  '92283': 'Imperial',

  // 935 spans LA / Kern / Inyo / Mono — map Kern ZIPs exactly.
  '93501': 'Kern',
  '93502': 'Kern',
  '93504': 'Kern',
  '93505': 'Kern',
  '93516': 'Kern',
  '93518': 'Kern',
  '93519': 'Kern',
  '93523': 'Kern',
  '93524': 'Kern',
  '93527': 'Kern',
  '93528': 'Kern',
  '93531': 'Kern',
  '93555': 'Kern',
  '93556': 'Kern',
  '93560': 'Kern',
  '93561': 'Kern',
  '93581': 'Kern',
  '93596': 'Kern',

  // 945: Alameda
  '94501': 'Alameda',
  '94502': 'Alameda',
  '94536': 'Alameda',
  '94537': 'Alameda',
  '94538': 'Alameda',
  '94539': 'Alameda',
  '94540': 'Alameda',
  '94541': 'Alameda',
  '94542': 'Alameda',
  '94543': 'Alameda',
  '94544': 'Alameda',
  '94545': 'Alameda',
  '94546': 'Alameda',
  '94550': 'Alameda',
  '94551': 'Alameda',
  '94552': 'Alameda',
  '94555': 'Alameda',
  '94557': 'Alameda',
  '94560': 'Alameda',
  '94566': 'Alameda',
  '94568': 'Alameda',
  '94577': 'Alameda',
  '94578': 'Alameda',
  '94579': 'Alameda',
  '94580': 'Alameda',
  '94586': 'Alameda',
  '94587': 'Alameda',
  '94588': 'Alameda',

  // 945: Contra Costa
  '94505': 'Contra Costa',
  '94506': 'Contra Costa',
  '94507': 'Contra Costa',
  '94509': 'Contra Costa',
  '94511': 'Contra Costa',
  '94513': 'Contra Costa',
  '94514': 'Contra Costa',
  '94516': 'Contra Costa',
  '94517': 'Contra Costa',
  '94518': 'Contra Costa',
  '94519': 'Contra Costa',
  '94520': 'Contra Costa',
  '94521': 'Contra Costa',
  '94522': 'Contra Costa',
  '94523': 'Contra Costa',
  '94524': 'Contra Costa',
  '94525': 'Contra Costa',
  '94526': 'Contra Costa',
  '94527': 'Contra Costa',
  '94528': 'Contra Costa',
  '94529': 'Contra Costa',
  '94530': 'Contra Costa',
  '94531': 'Contra Costa',
  '94547': 'Contra Costa',
  '94548': 'Contra Costa',
  '94549': 'Contra Costa',
  '94553': 'Contra Costa',
  '94556': 'Contra Costa',
  '94561': 'Contra Costa',
  '94563': 'Contra Costa',
  '94564': 'Contra Costa',
  '94565': 'Contra Costa',
  '94569': 'Contra Costa',
  '94570': 'Contra Costa',
  '94572': 'Contra Costa',
  '94575': 'Contra Costa',
  '94582': 'Contra Costa',
  '94583': 'Contra Costa',
  '94595': 'Contra Costa',
  '94596': 'Contra Costa',
  '94597': 'Contra Costa',
  '94598': 'Contra Costa',

  // 945: Solano
  '94510': 'Solano',
  '94512': 'Solano',
  '94533': 'Solano',
  '94534': 'Solano',
  '94535': 'Solano',
  '94571': 'Solano',
  '94585': 'Solano',
  '94589': 'Solano',
  '94590': 'Solano',
  '94591': 'Solano',
  '94592': 'Solano',

  // 945: Napa
  '94503': 'Napa',
  '94508': 'Napa',
  '94515': 'Napa',
  '94558': 'Napa',
  '94559': 'Napa',
  '94562': 'Napa',
  '94567': 'Napa',
  '94573': 'Napa',
  '94574': 'Napa',
  '94576': 'Napa',
  '94581': 'Napa',
  '94599': 'Napa',

  // 956/957: Sacramento
  '95608': 'Sacramento',
  '95609': 'Sacramento',
  '95610': 'Sacramento',
  '95611': 'Sacramento',
  '95615': 'Sacramento',
  '95621': 'Sacramento',
  '95624': 'Sacramento',
  '95626': 'Sacramento',
  '95628': 'Sacramento',
  '95630': 'Sacramento',
  '95632': 'Sacramento',
  '95638': 'Sacramento',
  '95639': 'Sacramento',
  '95641': 'Sacramento',
  '95652': 'Sacramento',
  '95655': 'Sacramento',
  '95660': 'Sacramento',
  '95662': 'Sacramento',
  '95670': 'Sacramento',
  '95673': 'Sacramento',
  '95683': 'Sacramento',
  '95690': 'Sacramento',
  '95693': 'Sacramento',

  // 956/957: Placer
  '95602': 'Placer',
  '95603': 'Placer',
  '95604': 'Placer',
  '95648': 'Placer',
  '95650': 'Placer',
  '95658': 'Placer',
  '95661': 'Placer',
  '95663': 'Placer',
  '95677': 'Placer',
  '95678': 'Placer',
  '95713': 'Placer',
  '95746': 'Placer',
  '95747': 'Placer',
  '95765': 'Placer',

  // 956/957: Yolo
  '95605': 'Yolo',
  '95606': 'Yolo',
  '95607': 'Yolo',
  '95612': 'Yolo',
  '95616': 'Yolo',
  '95617': 'Yolo',
  '95618': 'Yolo',
  '95627': 'Yolo',
  '95637': 'Yolo',
  '95645': 'Yolo',
  '95653': 'Yolo',
  '95679': 'Yolo',
  '95691': 'Yolo',
  '95694': 'Yolo',
  '95695': 'Yolo',
  '95697': 'Yolo',
  '95698': 'Yolo',
  '95776': 'Yolo',

  // 956/957: El Dorado
  '95613': 'El Dorado',
  '95614': 'El Dorado',
  '95619': 'El Dorado',
  '95623': 'El Dorado',
  '95633': 'El Dorado',
  '95634': 'El Dorado',
  '95635': 'El Dorado',
  '95636': 'El Dorado',
  '95651': 'El Dorado',
  '95664': 'El Dorado',
  '95667': 'El Dorado',
  '95672': 'El Dorado',
  '95682': 'El Dorado',
  '95684': 'El Dorado',
  '95709': 'El Dorado',
  '95726': 'El Dorado',
  '95762': 'El Dorado',

  // 956: Solano
  '95620': 'Solano',
  '95625': 'Solano',
  '95687': 'Solano',
  '95688': 'Solano',
  '95696': 'Solano',

  // 950 mixed
  '95002': 'Santa Clara',
  '95008': 'Santa Clara',
  '95014': 'Santa Clara',
  '95030': 'Santa Clara',
  '95032': 'Santa Clara',
  '95035': 'Santa Clara',
  '95037': 'Santa Clara',
  '95050': 'Santa Clara',
  '95051': 'Santa Clara',
  '95054': 'Santa Clara',
  '95070': 'Santa Clara',
  '95003': 'Santa Cruz',
  '95005': 'Santa Cruz',
  '95006': 'Santa Cruz',
  '95007': 'Santa Cruz',
  '95010': 'Santa Cruz',
  '95018': 'Santa Cruz',
  '95019': 'Santa Cruz',
  '95060': 'Santa Cruz',
  '95062': 'Santa Cruz',
  '95064': 'Santa Cruz',
  '95065': 'Santa Cruz',
  '95066': 'Santa Cruz',
  '95073': 'Santa Cruz',
  '95076': 'Santa Cruz',
  '95023': 'San Benito',
  '95004': 'Monterey',
  '95012': 'Monterey',
  '95039': 'Monterey',

  // 953 mixed
  '95307': 'Stanislaus',
  '95313': 'Stanislaus',
  '95316': 'Stanislaus',
  '95319': 'Stanislaus',
  '95323': 'Stanislaus',
  '95326': 'Stanislaus',
  '95328': 'Stanislaus',
  '95329': 'Stanislaus',
  '95350': 'Stanislaus',
  '95351': 'Stanislaus',
  '95354': 'Stanislaus',
  '95355': 'Stanislaus',
  '95356': 'Stanislaus',
  '95357': 'Stanislaus',
  '95358': 'Stanislaus',
  '95361': 'Stanislaus',
  '95363': 'Stanislaus',
  '95367': 'Stanislaus',
  '95368': 'Stanislaus',
  '95380': 'Stanislaus',
  '95382': 'Stanislaus',
  '95386': 'Stanislaus',
  '95387': 'Stanislaus',
  '95301': 'Merced',
  '95303': 'Merced',
  '95312': 'Merced',
  '95315': 'Merced',
  '95317': 'Merced',
  '95322': 'Merced',
  '95324': 'Merced',
  '95333': 'Merced',
  '95334': 'Merced',
  '95340': 'Merced',
  '95341': 'Merced',
  '95343': 'Merced',
  '95344': 'Merced',
  '95348': 'Merced',
  '95360': 'Merced',
  '95365': 'Merced',
  '95369': 'Merced',
  '95374': 'Merced',
  '95388': 'Merced',
  '95310': 'Tuolumne',
  '95321': 'Tuolumne',
  '95327': 'Tuolumne',
  '95370': 'Tuolumne',
  '95372': 'Tuolumne',
  '95379': 'Tuolumne',
  '95383': 'Tuolumne',
  '95311': 'Mariposa',
  '95318': 'Mariposa',
  '95338': 'Mariposa',
  '95345': 'Mariposa',
  '95304': 'San Joaquin',
  '95330': 'San Joaquin',
  '95336': 'San Joaquin',
  '95337': 'San Joaquin',
  '95366': 'San Joaquin',
  '95376': 'San Joaquin',
  '95377': 'San Joaquin',
  '95391': 'San Joaquin',
};

const normalizeCityKey = (cityName: string) =>
  String(cityName || '')
    .toLowerCase()
    .replace(/^city\s+of\s+/i, '')
    .replace(/[^a-z0-9\s'-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const extractZip5 = (zipRaw: unknown) => String(zipRaw || '').match(/\d{5}/)?.[0] || '';

export function findCountyByCity(cityName: string): string | null {
  const normalizedCity = normalizeCityKey(cityName);
  if (!normalizedCity) return null;
  return cityToCounty[normalizedCity] || null;
}

export function findCountyByZip(zipRaw: unknown): string | null {
  const zip = extractZip5(zipRaw);
  if (!zip) return null;
  return ZIP5_TO_COUNTY[zip] || ZIP3_TO_COUNTY[zip.slice(0, 3)] || null;
}

export function findCountyByCityAndZip(cityRaw?: unknown, zipRaw?: unknown): string | null {
  const zip = extractZip5(zipRaw);
  const zip5County = zip ? ZIP5_TO_COUNTY[zip] || null : null;
  if (zip5County) return zip5County;
  const cityCounty = findCountyByCity(String(cityRaw || ''));
  if (cityCounty) return cityCounty;
  return zip ? ZIP3_TO_COUNTY[zip.slice(0, 3)] || null : null;
}

// Function to get all cities in a specific county
export function getCitiesInCounty(countyName: string): string[] {
  return Object.entries(cityToCounty)
    .filter(([_, county]) => county === countyName)
    .map(([city, _]) => city)
    .sort();
}

// Function to search cities by partial name
export function searchCities(searchTerm: string): Array<{city: string, county: string}> {
  const normalizedSearch = searchTerm.toLowerCase().trim();
  
  if (normalizedSearch.length < 2) return [];
  
  return Object.entries(cityToCounty)
    .filter(([city, _]) => city.includes(normalizedSearch))
    .map(([city, county]) => ({ city, county }))
    .sort((a, b) => a.city.localeCompare(b.city))
    .slice(0, 20); // Limit results
}